"""Canonical GTSRB class labels in the benchmark's numeric order."""

GTSRB_LABELS = (
    "Speed limit (20 km/h)",
    "Speed limit (30 km/h)",
    "Speed limit (50 km/h)",
    "Speed limit (60 km/h)",
    "Speed limit (70 km/h)",
    "Speed limit (80 km/h)",
    "End of speed limit (80 km/h)",
    "Speed limit (100 km/h)",
    "Speed limit (120 km/h)",
    "No passing",
    "No passing for vehicles over 3.5 metric tons",
    "Right-of-way at the next intersection",
    "Priority road",
    "Yield",
    "Stop",
    "No vehicles",
    "Vehicles over 3.5 metric tons prohibited",
    "No entry",
    "General caution",
    "Dangerous curve to the left",
    "Dangerous curve to the right",
    "Double curve",
    "Bumpy road",
    "Slippery road",
    "Road narrows on the right",
    "Road work",
    "Traffic signals",
    "Pedestrians",
    "Children crossing",
    "Bicycles crossing",
    "Beware of ice/snow",
    "Wild animals crossing",
    "End of all speed and passing limits",
    "Turn right ahead",
    "Turn left ahead",
    "Ahead only",
    "Go straight or right",
    "Go straight or left",
    "Keep right",
    "Keep left",
    "Roundabout mandatory",
    "End of no passing",
    "End of no passing by vehicles over 3.5 metric tons",
)

GTSRB_LABELS_ZH = (
    "限速 20 km/h",
    "限速 30 km/h",
    "限速 50 km/h",
    "限速 60 km/h",
    "限速 70 km/h",
    "限速 80 km/h",
    "解除限速 80 km/h",
    "限速 100 km/h",
    "限速 120 km/h",
    "禁止超车",
    "禁止 3.5 吨以上车辆超车",
    "前方路口优先通行",
    "优先道路",
    "减速让行",
    "停车让行",
    "禁止车辆通行",
    "禁止 3.5 吨以上车辆通行",
    "禁止驶入",
    "注意危险",
    "左侧急弯",
    "右侧急弯",
    "连续弯路",
    "路面不平",
    "路面湿滑",
    "右侧道路变窄",
    "道路施工",
    "交通信号灯",
    "行人",
    "儿童横穿",
    "自行车横穿",
    "注意冰雪",
    "注意野生动物",
    "解除所有限速和超车禁令",
    "前方右转",
    "前方左转",
    "仅限直行",
    "直行或右转",
    "直行或左转",
    "靠右行驶",
    "靠左行驶",
    "环岛行驶",
    "解除禁止超车",
    "解除 3.5 吨以上车辆禁止超车",
)
