"""add file_cache table

Revision ID: a103613300bc
Revises: a07b53a84e0c
Create Date: 2026-07-09 15:48:52.913598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a103613300bc'
down_revision: Union[str, None] = 'a07b53a84e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False, comment='文件二进制数据'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_extension', sa.String(length=50), nullable=False, comment='文件扩展名'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='文件大小（字节）'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='上传用户名'),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True, comment='上传时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_cache_uploaded_at'), 'file_cache', ['uploaded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_cache_uploaded_at'), table_name='file_cache')
    op.drop_table('file_cache')
    # ### end Alembic commands ###
