"""init: create users, detection_records, training_tasks tables

Revision ID: d1589e7509ba
Revises: 0965f9fea370
Create Date: 2026-07-07 17:06:13.118161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1589e7509ba'
down_revision: Union[str, None] = '0965f9fea370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
